spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/springboot-aws
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # application-oauth.yaml을 포함하도록 profile 설정
  profiles:
    include: oauth